name: Test BaseLinker Inventory Update

on:
  workflow_dispatch:   # ręczne odpalenie z zakładki Actions
  schedule:
    - cron: "0 * * * *"   # automatycznie co godzinę (UTC) – możesz zmienić albo usunąć

jobs:
  update-test-product:
    runs-on: ubuntu-latest

    steps:
    - name: Update stock in BaseLinker inventory
      run: |
        curl -X POST "https://api.baselinker.com/connector.php" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -H "X-BLToken: ${{ secrets.BL_TOKEN }}" \
        --data-urlencode 'method=updateInventoryProductsStock' \
        'parameters={"inventory_id":53339,"products":[{"product_id":358238153,"variant_id":0,"stock":{"bl_72390":5}}]}'

