name: Test BaseLinker Inventory Update

on:
  workflow_dispatch:   # ręczne odpalenie z zakładki Actions
  schedule:
    - cron: "*/1 * * * *" 

jobs:
  update-test-product:
    runs-on: ubuntu-latest

    steps:
    - name: Update stock in BaseLinker inventory
      run: |
        curl -X POST "https://api.baselinker.com/connector.php" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -H "X-BLToken: ${{ secrets.BL_TOKEN }}" \
        --data-urlencode 'method=updateInventoryProductsStock' \
        --data-urlencode 'parameters={"inventory_id":"53339","products":{"358238153":{"bl_72390":5}}}'
