name: Test BaseLinker Storages

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"   # możesz na razie zakomentować, żeby nie leciało co godzinę

jobs:
  list-storages:
    runs-on: ubuntu-latest

    steps:
    - name: Call BaseLinker getStoragesList
      run: |
        curl -X POST "https://api.baselinker.com/connector.php" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -H "X-BLToken: ${{ secrets.BL_TOKEN }}" \
        --data-urlencode 'method=getStoragesList'
