name: Test BaseLinker Update

on:
  workflow_dispatch:   # pozwala odpalić ręcznie
  schedule:
    - cron: "0 * * * *"   # odpala co godzinę (na razie na testy)
                          # później ustawimy np. */15 * * * *

jobs:
  update-test-product:
    runs-on: ubuntu-latest

    steps:
    - name: Call BaseLinker API
      run: |
        curl -X POST "https://api.baselinker.com/connector.php" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -H "X-BLToken: ${{ secrets.BL_TOKEN }}" \
        --data-urlencode 'method=updateProductsQuantity' \
        --data-urlencode 'parameters={"storage_id":"bl_72390","products":[["358238153",0,5]]}'
